import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/ui/sidebar";
import {cn} from "@/lib/utils";
import Providers from "@/app/utils/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="font-jalnan">
      <body
          className={cn(
              "min-h-screen w-full bg-white text-black flex ",
              {"debug-screens": process.env.NODE_ENV === "development"}
          )}
      >
      {/* Sidebar */}
      <Sidebar/>
      {/* main page */}
      <Providers><div className="p-8 w-full">{children}</div></Providers>
      </body>
    </html>
  );
}
